# Generated by Django 4.2 on 2023-12-13 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name=' الاسم')),
                ('national_id', models.CharField(blank=True, max_length=14, null=True, verbose_name=' الرقم القومى')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name=' رقم التليفون ')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='  العنوان ')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='  ملاحظات ')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الاضافة')),
            ],
            options={
                'verbose_name': '   حساب',
                'verbose_name_plural': '  حسابات المرضى',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الزيارة')),
                ('visit_type', models.CharField(blank=True, choices=[('N', 'جديد'), ('R', 'اعادة')], default='N', max_length=10, null=True, verbose_name=' نوع الزيارة')),
                ('diagnosis', models.TextField(blank=True, max_length=1000, null=True, verbose_name='  التشخيص')),
                ('session_file', models.FileField(upload_to='session_files/')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.patientprofile', verbose_name='حساب المريض')),
            ],
            options={
                'verbose_name': '   زيارة',
                'verbose_name_plural': '  الزيارات',
            },
        ),
        migrations.CreateModel(
            name='Paid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(blank=True, default=1, null=True, verbose_name=' المدفوع')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الدفع')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.session', verbose_name=' الزيارة')),
            ],
            options={
                'verbose_name': ' دفعة',
                'verbose_name_plural': ' المدفوعات',
            },
        ),
        migrations.CreateModel(
            name='Medicin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='  اسم العلاج')),
                ('times', models.IntegerField(blank=True, default=1, null=True, verbose_name='عدد المرات')),
                ('taken_time', models.CharField(blank=True, choices=[('a', 'بعد الاكل'), ('b', 'قبل الاكل'), ('c', 'قبل الاكل وبعده'), ('d', 'قبل النوم'), ('e', ' صباحا'), ('f', ' مساءا'), ('g', ' صباحا ومساءا'), ('h', '  كل 6 ساعات'), ('i', '  كل 12 ساعة'), ('j', '  كل 24 ساعة'), ('k', '  كل 48 ساعة')], default='a', max_length=10, null=True, verbose_name='  التوقيت')),
                ('status', models.BooleanField(blank=True, default=True, null=True, verbose_name='الحالة')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.session', verbose_name=' الزيارة')),
            ],
            options={
                'verbose_name': '   علاج',
                'verbose_name_plural': '  العلاج',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='session_files/')),
                ('datet_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.session', verbose_name=' الزيارة')),
            ],
            options={
                'verbose_name': '   ملف',
                'verbose_name_plural': '  الملفات',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(blank=True, default=1, null=True, verbose_name=' تكلفة')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الاستحقاق')),
                ('reason', models.CharField(blank=True, default='كشف', max_length=200, null=True, verbose_name='  سبب التكلفة')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.session', verbose_name=' الزيارة')),
            ],
            options={
                'verbose_name': ' تكلفة',
                'verbose_name_plural': ' مصاريف',
            },
        ),
    ]
