# Generated by Django 4.2 on 2023-12-13 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.patientprofile', verbose_name='حساب المريض'),
        ),
        migrations.AddField(
            model_name='file',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.patientprofile', verbose_name='حساب المريض'),
        ),
        migrations.AddField(
            model_name='medicin',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.patientprofile', verbose_name='حساب المريض'),
        ),
        migrations.AddField(
            model_name='paid',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.patientprofile', verbose_name='حساب المريض'),
        ),
    ]
