# Generated by Django 4.2 on 2023-12-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0004_alter_file_file_alter_session_session_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicin',
            name='status',
        ),
        migrations.AddField(
            model_name='medicin',
            name='day_times',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='عدد ايام المواظبة'),
        ),
    ]
