# Generated by Django 4.2 on 2023-12-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0005_remove_medicin_status_medicin_day_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.BooleanField(default=True, verbose_name='  الحالة'),
        ),
        migrations.AlterField(
            model_name='file',
            name='title',
            field=models.CharField(max_length=255, verbose_name='  وصف'),
        ),
        migrations.AlterField(
            model_name='medicin',
            name='taken_time',
            field=models.CharField(blank=True, choices=[('a', 'بعد الاكل'), ('b', 'قبل الاكل'), ('c', 'قبل الاكل وبعده'), ('d', 'قبل النوم'), ('e', ' صباحا'), ('f', ' مساءا'), ('g', ' صباحا ومساءا'), ('h', '  كل 6 ساعات'), ('i', '  كل 12 ساعة'), ('j', '  كل 24 ساعة'), ('k', '  كل 48 ساعة')], max_length=10, null=True, verbose_name='  التوقيت'),
        ),
    ]
