# Generated by Django 4.2 on 2023-12-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0006_alter_file_status_alter_file_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name=' الاسم')),
                ('national_id', models.CharField(blank=True, max_length=14, null=True, verbose_name=' الرقم القومى')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name=' رقم التليفون ')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='  العنوان ')),
                ('status', models.BooleanField(default=False, verbose_name='  حالة الانتهاء ')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الاضافة')),
                ('specific_time', models.TimeField(blank=True, null=True, verbose_name='  الوقت')),
            ],
            options={
                'verbose_name': '   حجز',
                'verbose_name_plural': '   الحجوزات',
            },
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '   ملف', 'verbose_name_plural': ' (تحاليل , اشاعات , ...) الملفات'},
        ),
    ]
