# Generated by Django 4.2 on 2023-12-31 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0007_reserve_alter_file_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='specific_time',
            field=models.TimeField(blank=True, default='00-00-00', null=True, verbose_name='  الوقت'),
        ),
    ]
