# Generated by Django 4.2 on 2024-01-11 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0008_alter_reserve_specific_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserve',
            options={'ordering': ('status',), 'verbose_name': '   حجز', 'verbose_name_plural': '   الحجوزات'},
        ),
        migrations.AddField(
            model_name='reserve',
            name='visit_type',
            field=models.CharField(blank=True, choices=[('N', 'جديد'), ('R', 'اعادة')], default='N', max_length=10, null=True, verbose_name=' نوع الزيارة'),
        ),
        migrations.AlterField(
            model_name='session',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.patient', verbose_name='الحالة '),
        ),
        migrations.AlterField(
            model_name='session',
            name='visit_type',
            field=models.CharField(blank=True, default='N', editable=False, max_length=10, null=True, verbose_name=' نوع الزيارة'),
        ),
    ]
