# Generated by Django 4.2 on 2024-01-12 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0009_alter_reserve_options_reserve_visit_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='session_file',
        ),
    ]
