# Generated by Django 4.2 on 2024-01-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0010_remove_session_session_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_session_price', models.IntegerField(blank=True, default=1, null=True, verbose_name='عدد المرات')),
                ('return_session_price', models.IntegerField(blank=True, default=1, null=True, verbose_name='عدد المرات')),
            ],
            options={
                'verbose_name': '   حسبة',
                'verbose_name_plural': ' اسعار الزيارات',
            },
        ),
    ]
