# Generated by Django 4.2 on 2024-01-13 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0012_alter_sessionprice_new_session_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatentPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(blank=True, default=1, null=True, verbose_name=' المدفوع')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name=' تاريخ الدفع')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maindata.patient', verbose_name=' الحالة')),
            ],
            options={
                'verbose_name': ' دفعة',
                'verbose_name_plural': ' المدفوع لاحقا',
            },
        ),
    ]
