# Generated by Django 4.2 on 2024-01-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindata', '0014_alter_session_visit_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatentPay',
        ),
    ]
